### ISSUE TITLE
listing versions of orb "circleci/welcome-orb" without source panic: errors: *target must be interface or implement error

### ISSUE THREAD

**Issue by jkzilla** [circle-makotom/orbs-sync#4] opened 2022-02-14 22:53 UTC
https://github.com/circle-makotom/orbs-sync to execute the orb-sync command, but that has started giving an error when trying to execute against the welcome-orb:

collector: 2022/02/14 00:01:36.614205 listing versions of orb "circleci/welcome-orb" without source
panic: errors: *target must be interface or implement error

goroutine 1 [running]:
errors.As({0x9146e0, 0xc000684b10}, {0x7f3200, 0xc0003c91c0})
/usr/local/go/src/errors/wrap.go:88 +0x3d2

**Comment by kelvintaywl** [comment] 2022-02-15 00:55
for context, the above was seen by a user using version `0.1.52-8633314` ([this release](https://github.com/circle-makotom/orbs-sync/releases/tag/0.1.52-8633314)).

Looking at #2 , i understand there were error handling updates on _collector.go_ so i wonder if the user seeing the errors above can use the later releases seen at https://github.com/circle-makotom/orbs-sync/releases

**Comment by makotom** [comment] 2022-02-17 04:05
This should be now fixed in `0.2.100-7f022aa` (#5).

Please note that the user would still see an error in the situation where the panic error was thrown. The error should be caused by an irregular response coming from the server side. Be advised to review logs on the server side - ideally server-side logs snapshot after running the application with `--debug` option enabled.

**Closed as completed by makotom** 2022-02-17 04:05 UTC
